"""Stable enum values used by every integration contract."""

from enum import StrEnum


class ConnectorType(StrEnum):
    INTERNAL_OS = "INTERNAL_OS"
    EXTERNAL_API = "EXTERNAL_API"
    FILE_IMPORT = "FILE_IMPORT"
    FILE_EXPORT = "FILE_EXPORT"
    DATABASE = "DATABASE"
    WEBHOOK = "WEBHOOK"
    AI_PROVIDER = "AI_PROVIDER"
    MESSAGE = "MESSAGE"
    CUSTOM = "CUSTOM"


class ConnectorStatus(StrEnum):
    REGISTERED = "REGISTERED"
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    DISABLED = "DISABLED"
    ERROR = "ERROR"


class HealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    UNKNOWN = "UNKNOWN"
    DISABLED = "DISABLED"


class MessageStatus(StrEnum):
    CREATED = "CREATED"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"


class SyncStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CONFLICT = "CONFLICT"
    CANCELLED = "CANCELLED"


class ErrorCode(StrEnum):
    CONNECTOR_NOT_FOUND = "CONNECTOR_NOT_FOUND"
    CONNECTOR_DISABLED = "CONNECTOR_DISABLED"
    CONNECTION_FAILED = "CONNECTION_FAILED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    TIMEOUT = "TIMEOUT"
    RATE_LIMITED = "RATE_LIMITED"
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    IMPORT_FAILED = "IMPORT_FAILED"
    EXPORT_FAILED = "EXPORT_FAILED"
    TRANSFORMATION_FAILED = "TRANSFORMATION_FAILED"
    SYNC_FAILED = "SYNC_FAILED"
    EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE"
    SAFETY_REJECTED = "SAFETY_REJECTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
